### ISSUE TITLE
differential steering  dp=2.4

### ISSUE THREAD

**Issue by bao666liang** [samiusn/materes#1]
I want to ask how to determine the dp of differential steering，I see that the dp written in the code is 2.4，But the effect is not good when tracking circular tracks, I really hope to get your answer.

**Comment by samiusn** [comment]
The value of dp is taken from the vrx seadrone physical definition. I think there is nothing much to determine as it is physical property of the drone.
As far I understand more control on circle can be achieved if rotation of the thruster is being added. Hope that helps.

**Comment by bao666liang** [comment]
Thank you very much for your answer. 
So you mean that it is impossible to track a circle only by differential steering   ( Tr=dp * (Ts -Tp) )  ?
It is necessary to rely on the rotation of the thruster to achieve accurate steering and track the arc trajectory  ?

**Comment by samiusn** [comment]
I guess "impossible" wont be correct word. It is possible but for sharp turn rotation of thruster is more accurate.
You can think of rotation point(center of rotation) in both situation and very much understand why.
Again going back to your main concern it should work ingeneral circular tracks. You may need to tune wight matrices. 
![image](https://user-images.githubusercontent.com/78034055/198208398-72d72a82-4496-4467-a27e-1388eea21318.png)

**Comment by bao666liang** [comment]
Yes, it is a parameter problem. Thank you very much. I set the weight of Q matrix to 500, Np to 50, Nc to 15, and T to 0.5s. It runs well, but there is always an error of 0.6m. I also used ROS robot_ localization pkg.
But I can't find which file of VRX pkg defines the dp (=2.4) parameter. Could you give a prompt?
It's a bit disturbing to ask questions all the time, ha ha
![1](https://user-images.githubusercontent.com/91942808/198213000-ab3cc512-38cb-46e6-a59a-baa25aaccd2a.jpg)

**Comment by samiusn** [comment]
Well dont worry about questions, I know the situation as I did not get answers from 2 people when I was working.
Any way I can definetly see that you are working way a head what I did as my work was not much into accuracy. But I can recall that it was some where in the GAZEBO models or URDF fiels I got the values. Please keep in mind that I tuned it here and there so in the code it may not be the same as URDF.
You are welcome to ask questions dont worry about that. I am family guy with job so may be late some times to answer.

**Comment by bao666liang** [comment]
Ha ha, thank you for your warm reply, but I should have no problem. Thank you again for your help, which crossed thousands of miles
